### PR TITLE
Sourcepath

### PR DESCRIPTION
**Pull request by llgcode**
add the ability to define a sourcepath to jdb. Works well with an eclipse hello world java project. Also update config so that it compiles with latest config recommandation

### CODE REVIEW

**Comment by llgcode** [comment]
this pr fixes #1

**Comment by DonJayamanne** [comment]
@llgcode   Code has been merged, please could you test the latest master branch and let me know if all is ok.
Thanks for your effort (updated readme.md to recognize your contribution)

**Comment by llgcode** [comment]
Works for me on the latest master branch. Thanks @DonJayamanne for merging.

**Comment by llgcode** [comment]
This pr fixes #22

**Pull request merged**
