### PR TITLE
Ability to pass arguments to java application

### PR DESCRIPTION
**Pull request by dueckminor**
This implements the following feature request:
https://github.com/DonJayamanne/javaVSCode/issues/21

### CODE REVIEW

**Comment by faustinoaq** [comment]
Thanks you!

**Comment by DonJayamanne** [comment]
@faustinoaq do you want me to create a new release?

**Comment by DonJayamanne** [comment]
Let me know if and when you would like me to do so

**Comment by faustinoaq** [comment]
@DonJayamanne yes, We want :smile:

**Pull request merged**
